# kube/ansible-runner-nix.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ansible-runner-nix
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  containers:
    - name: runner
      image: nix:local
      imagePullPolicy: Never
      command: ["nix-shell", "/shell.nix", "--pure", "--command", "sleep 1d"] # to keep the pod running for me to work with it
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: workspace
      hostPath:
        path: /workspace
        type: Directory
