# config/multipass-host.yaml

# Enable Ansible ssh access using ansible user public key. Update with Your actual key.
runcmd:
  - echo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFy/uG6GOFYpjXFslP3TjM0CmxL1dbM0DPmJRwkvPKIF ubuntu@ansible-runner >> /home/ubuntu/.ssh/authorized_keys
