# config\multipass-ansible-runner.yaml

package_update: true
package_upgrade: true

packages:
  - coreutils
  - findutils
  - gawk
  - jq
  - tree
  - wget
  - curl
  - zip 
  - unzip
  - iputils-ping
  - iputils-tracepath
  - vim-full
  - emacs-nox
  - sudo
  - git
  - python3-pip
  - ansible

lxd:
  init:
    storage_backend: dir

ansible:
  install_method: apt
  package_name: ansible
  run_user: ubuntu
  galaxy:
    actions:
      - ["ansible-galaxy", "collection", "install", "zabbix.zabbix"]

write_files:
- content: |
    Install nix: 
    curl -L https://nixos.org/nix/install | sh

    Then:
    cd /workspace
    nix-shell config/nix/shell.nix
  path: /home/ubuntu/nix-install.md

runcmd:
  - [ mkdir, -p, /workspace ]
