- name: Create admin user
  user:
    name: "{{ admin_user.name }}"
    shell: /bin/bash
    groups: admin
    append: yes
    create_home: yes
    password: "{{ admin_password_hash }}"

- name: Force password reset on first login (optional)
  command: chage -d 0 {{ admin_user.name }}
  when: admin_user.force_password_reset | default(false)

- name: Add SSH key for admin user
  authorized_key:
    user: "{{ admin_user.name }}"
    state: present
    key: "{{ lookup('file', 'files/home/' ~ admin_user.name ~ '/ssh/id_ed25519.pub') }}"
