# Run this with:
# ansible-playbook ansible-ping-local.yaml

---

- name: "ping local connection"
  hosts: localhost
  gather_facts: false
  connection: local

  tasks: 
    - name: ping
      ansible.builtin.ping: