---

- name: Install and configure LXD on Ubuntu host
  hosts:
    - site-a-host
    - site-z-host

  become: true
  vars:
    image_server_name: "https://cloud-images.ubuntu.com/releases/"

    lxd_preseed_config: |
      config: {}
      networks:
      - config:
          ipv4.address: auto
          ipv4.nat: "true"
          ipv6.address: auto
        description: ""
        name: lxdbr0
        type: ""
        project: default
      storage_pools:
      - config: {}
        description: ""
        name: default
        driver: dir
      storage_volumes: []
      profiles:
      - config: {}
        description: ""
        devices:
          eth0:
            name: eth0
            network: lxdbr0
            type: nic
          root:
            path: /
            pool: default
            type: disk
        name: default
      projects: []
      cluster: null

  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Snapd bindings for python
      apt:
        name: 
          - snapd 
        state: present

    - name: Install LXD service via Snap 
      snap:
        name: lxd 
        classic: yes 
        state: present 

    - name: Ensure LXD service is started and enabled
      systemd:
        name: snap.lxd.daemon.service
        state: started 
        enabled: yes 

    - name: Initialize LXD with preseed configuration
      shell: "printf '{{ lxd_preseed_config }}' | lxd init --preseed"
      args:
        creates: /var/snap/lxd/common/lxd/lxd.db

    - block:
        - name: Check if the LXD image server remote exists
          shell: lxc remote list | grep -w "{{ image_server_name }}"
          register: remote_check
          changed_when: false
          failed_when: remote_check.rc not in [0, 1] # Fail only if there's an unexpected error

      rescue:
        - name: Display current LXD remote list for diagnostics 
          shell: lxc remote list 
          register: remote_list
          changed_when: false 

        - name: Log failure and show available remotes 
          debug:
            msg: |
              Failed to verify or add the remote '{{ image_server_name }}'.
              Current LXD remote list:
              {{ remote_list.stdout }}

    - name: Create a started container
      community.general.lxd_container:
        name: mycontainer
        ignore_volatile_options: true 
        state: started 
        source:
          type: image
          mode: pull
          server: "{{ image_server_name }}"
          protocol: simplestreams
          alias: "24.04"
        profiles: ["default"]
        wait_for_ipv4_addresses: true 
        timeout: 600

