---

# Verify: ansible-playbook exercise-configure-server-set.yaml -u root -C -D
# Apply:  ansible-playbook exercise-configure-server-set.yaml -u root

- hosts: exercise
  gather_facts: false
  become: true

  vars_files:
    - ../config/project-vars.env.yaml
    - ../config/var/default-admin-password.yaml

  vars:

  # collections:
  #   - zabbix.zabbix

  roles:
    - configure_admin_user
    - configure_ntp_crony
    - role: zabbix.zabbix.agent
      vars:
        agent_variant: 2
        agent_param_server: "{{ zabbix_server_ip }}"
        agent_param_serveractive: "{{ zabbix_server_ip }}"
        zabbix_agent_hostname: "{{ inventory_hostname }}"

  tasks:
    # placeholder for custom, additional tasks