---

# Verify: ansible-playbook exercise-create-admin-user.yaml -u root -C -D
# Apply:  ansible-playbook exercise-create-admin-user.yaml -u root

- name: Configure admin user
  hosts:
    - hostname1
    - hostname2
    - hostname3
    - hostname4
    - hostname5

  become: true

  vars_files:
    - ../config/project-vars.env.yaml
    - ../config/var/default-admin-password.yaml

  roles:
    - configure_admin_user
