---

# Verify: ansible-playbook exercise-configure-chrony-service.yaml -u root -C -D
# Apply:  ansible-playbook exercise-configure-chrony-service.yaml -u root

- name: Configure NTP service Chrony
  hosts:
    - hostname1
    - hostname2
    - hostname3
    - hostname4
    - hostname5

  become: true
  vars_files:
    - ../config/project-vars.env.yaml

  roles:
    - configure_ntp_chrony
