---

# Verify: ansible-playbook configure-server-set.yaml -u root -C -D
# Apply:  ansible-playbook configure-server-set.yaml -u root

- hosts: exercise
  gather_facts: false
  become: true

  vars_files:
    - ../config/project-vars.env.yaml

#  vars:

  roles:
    - configure_admin_user
    - configure_ntp_crony
    - configure_zabbix_agent2

  tasks:
    # placeholder for custom, additional tasks