---

- name: Verify NTP configuration
  hosts:
    - hostname1
    - hostname2
    - hostname3
    - hostname4
    - hostname5
    #- test-host1
    #- zabbix-node

  become: true
  vars_files:
    - ../config/project-vars.env.yaml
  roles:
    - verify_ntp_config